/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _about_blank_h_
#define _about_blank_h_
//---------------------------------------------------------------------------------
extern const unsigned char about_blank[];
extern const int about_blank_size;
//---------------------------------------------------------------------------------
#endif //_about_blank_h_
//---------------------------------------------------------------------------------
