/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _app_download_h_
#define _app_download_h_
//---------------------------------------------------------------------------------
extern const unsigned char app_download[];
extern const int app_download_size;
//---------------------------------------------------------------------------------
#endif //_app_download_h_
//---------------------------------------------------------------------------------
