/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _app_tick_small_h_
#define _app_tick_small_h_
//---------------------------------------------------------------------------------
extern const unsigned char app_tick_small[];
extern const int app_tick_small_size;
//---------------------------------------------------------------------------------
#endif //_app_tick_small_h_
//---------------------------------------------------------------------------------
