/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _apps_updated_h_
#define _apps_updated_h_
//---------------------------------------------------------------------------------
extern const unsigned char apps_updated[];
extern const int apps_updated_size;
//---------------------------------------------------------------------------------
#endif //_apps_updated_h_
//---------------------------------------------------------------------------------
