/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _apps_table_blank_h_
#define _apps_table_blank_h_
//---------------------------------------------------------------------------------
extern const unsigned char apps_table_blank[];
extern const int apps_table_blank_size;
//---------------------------------------------------------------------------------
#endif //_apps_table_blank_h_
//---------------------------------------------------------------------------------
