/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _blue_dark_small_h_
#define _blue_dark_small_h_
//---------------------------------------------------------------------------------
extern const unsigned char blue_dark_small[];
extern const int blue_dark_small_size;
//---------------------------------------------------------------------------------
#endif //_blue_dark_small_h_
//---------------------------------------------------------------------------------
