/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_no_highlight_h_
#define _button_no_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_no_highlight[];
extern const int button_no_highlight_size;
//---------------------------------------------------------------------------------
#endif //_button_no_highlight_h_
//---------------------------------------------------------------------------------
