/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cancel_download_prompt_h_
#define _cancel_download_prompt_h_
//---------------------------------------------------------------------------------
extern const unsigned char cancel_download_prompt[];
extern const int cancel_download_prompt_size;
//---------------------------------------------------------------------------------
#endif //_cancel_download_prompt_h_
//---------------------------------------------------------------------------------
