/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cat_media_highlight_h_
#define _cat_media_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char cat_media_highlight[];
extern const int cat_media_highlight_size;
//---------------------------------------------------------------------------------
#endif //_cat_media_highlight_h_
//---------------------------------------------------------------------------------
