/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_keyboard_h_
#define _control_keyboard_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_keyboard[];
extern const int control_keyboard_size;
//---------------------------------------------------------------------------------
#endif //_control_keyboard_h_
//---------------------------------------------------------------------------------
