/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_gcn_h_
#define _control_gcn_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_gcn[];
extern const int control_gcn_size;
//---------------------------------------------------------------------------------
#endif //_control_gcn_h_
//---------------------------------------------------------------------------------
