/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _down_clear_highlight_h_
#define _down_clear_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char down_clear_highlight[];
extern const int down_clear_highlight_size;
//---------------------------------------------------------------------------------
#endif //_down_clear_highlight_h_
//---------------------------------------------------------------------------------
