/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _download_button_h_
#define _download_button_h_
//---------------------------------------------------------------------------------
extern const unsigned char download_button[];
extern const int download_button_size;
//---------------------------------------------------------------------------------
#endif //_download_button_h_
//---------------------------------------------------------------------------------
