/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _down_clear_h_
#define _down_clear_h_
//---------------------------------------------------------------------------------
extern const unsigned char down_clear[];
extern const int down_clear_size;
//---------------------------------------------------------------------------------
#endif //_down_clear_h_
//---------------------------------------------------------------------------------
