/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _download_button_highlight_h_
#define _download_button_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char download_button_highlight[];
extern const int download_button_highlight_size;
//---------------------------------------------------------------------------------
#endif //_download_button_highlight_h_
//---------------------------------------------------------------------------------
