/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _guy_settings_h_
#define _guy_settings_h_
//---------------------------------------------------------------------------------
extern const unsigned char guy_settings[];
extern const int guy_settings_size;
//---------------------------------------------------------------------------------
#endif //_guy_settings_h_
//---------------------------------------------------------------------------------
