/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_queue_h_
#define _help_queue_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_queue[];
extern const int help_queue_size;
//---------------------------------------------------------------------------------
#endif //_help_queue_h_
//---------------------------------------------------------------------------------
