/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_settings_7_h_
#define _help_settings_7_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_settings_7[];
extern const int help_settings_7_size;
//---------------------------------------------------------------------------------
#endif //_help_settings_7_h_
//---------------------------------------------------------------------------------
