/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_sorting_2_h_
#define _help_sorting_2_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_sorting_2[];
extern const int help_sorting_2_size;
//---------------------------------------------------------------------------------
#endif //_help_sorting_2_h_
//---------------------------------------------------------------------------------
