/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_controller_h_
#define _help_controller_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_controller[];
extern const int help_controller_size;
//---------------------------------------------------------------------------------
#endif //_help_controller_h_
//---------------------------------------------------------------------------------
