/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_apps_information_2_h_
#define _help_apps_information_2_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_apps_information_2[];
extern const int help_apps_information_2_size;
//---------------------------------------------------------------------------------
#endif //_help_apps_information_2_h_
//---------------------------------------------------------------------------------
