/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_apps_installed_h_
#define _help_apps_installed_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_apps_installed[];
extern const int help_apps_installed_size;
//---------------------------------------------------------------------------------
#endif //_help_apps_installed_h_
//---------------------------------------------------------------------------------
