/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_settings_3_h_
#define _help_settings_3_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_settings_3[];
extern const int help_settings_3_size;
//---------------------------------------------------------------------------------
#endif //_help_settings_3_h_
//---------------------------------------------------------------------------------
