/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _menu_loader_h_
#define _menu_loader_h_
//---------------------------------------------------------------------------------
extern const unsigned char menu_loader[];
extern const int menu_loader_size;
//---------------------------------------------------------------------------------
#endif //_menu_loader_h_
//---------------------------------------------------------------------------------
