/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _name_highlight_h_
#define _name_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char name_highlight[];
extern const int name_highlight_size;
//---------------------------------------------------------------------------------
#endif //_name_highlight_h_
//---------------------------------------------------------------------------------
