/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _setting_cross_h_
#define _setting_cross_h_
//---------------------------------------------------------------------------------
extern const unsigned char setting_cross[];
extern const int setting_cross_size;
//---------------------------------------------------------------------------------
#endif //_setting_cross_h_
//---------------------------------------------------------------------------------
