/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _thumbs_up_highlight_h_
#define _thumbs_up_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char thumbs_up_highlight[];
extern const int thumbs_up_highlight_size;
//---------------------------------------------------------------------------------
#endif //_thumbs_up_highlight_h_
//---------------------------------------------------------------------------------
