/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tool_tip_update_apps_h_
#define _tool_tip_update_apps_h_
//---------------------------------------------------------------------------------
extern const unsigned char tool_tip_update_apps[];
extern const int tool_tip_update_apps_size;
//---------------------------------------------------------------------------------
#endif //_tool_tip_update_apps_h_
//---------------------------------------------------------------------------------
