/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tooltip_help_h_
#define _tooltip_help_h_
//---------------------------------------------------------------------------------
extern const unsigned char tooltip_help[];
extern const int tooltip_help_size;
//---------------------------------------------------------------------------------
#endif //_tooltip_help_h_
//---------------------------------------------------------------------------------
