/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _app_question_h_
#define _app_question_h_
//---------------------------------------------------------------------------------
extern const unsigned char app_question[];
extern const int app_question_size;
//---------------------------------------------------------------------------------
#endif //_app_question_h_
//---------------------------------------------------------------------------------
