/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _apps_bottom_h_
#define _apps_bottom_h_
//---------------------------------------------------------------------------------
extern const unsigned char apps_bottom[];
extern const int apps_bottom_size;
//---------------------------------------------------------------------------------
#endif //_apps_bottom_h_
//---------------------------------------------------------------------------------
