/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _apps_start_sort_h_
#define _apps_start_sort_h_
//---------------------------------------------------------------------------------
extern const unsigned char apps_start_sort[];
extern const int apps_start_sort_size;
//---------------------------------------------------------------------------------
#endif //_apps_start_sort_h_
//---------------------------------------------------------------------------------
