/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _blue_light_small_h_
#define _blue_light_small_h_
//---------------------------------------------------------------------------------
extern const unsigned char blue_light_small[];
extern const int blue_light_small_size;
//---------------------------------------------------------------------------------
#endif //_blue_light_small_h_
//---------------------------------------------------------------------------------
