/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _blue_progress_h_
#define _blue_progress_h_
//---------------------------------------------------------------------------------
extern const unsigned char blue_progress[];
extern const int blue_progress_size;
//---------------------------------------------------------------------------------
#endif //_blue_progress_h_
//---------------------------------------------------------------------------------
