/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_yes_h_
#define _button_yes_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_yes[];
extern const int button_yes_size;
//---------------------------------------------------------------------------------
#endif //_button_yes_h_
//---------------------------------------------------------------------------------
