/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cat_utilities_h_
#define _cat_utilities_h_
//---------------------------------------------------------------------------------
extern const unsigned char cat_utilities[];
extern const int cat_utilities_size;
//---------------------------------------------------------------------------------
#endif //_cat_utilities_h_
//---------------------------------------------------------------------------------
