/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_classic_h_
#define _control_classic_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_classic[];
extern const int control_classic_size;
//---------------------------------------------------------------------------------
#endif //_control_classic_h_
//---------------------------------------------------------------------------------
