/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_nunchuck_h_
#define _control_nunchuck_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_nunchuck[];
extern const int control_nunchuck_size;
//---------------------------------------------------------------------------------
#endif //_control_nunchuck_h_
//---------------------------------------------------------------------------------
