/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_guitar_h_
#define _control_guitar_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_guitar[];
extern const int control_guitar_size;
//---------------------------------------------------------------------------------
#endif //_control_guitar_h_
//---------------------------------------------------------------------------------
