/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_wiimote_4_h_
#define _control_wiimote_4_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_wiimote_4[];
extern const int control_wiimote_4_size;
//---------------------------------------------------------------------------------
#endif //_control_wiimote_4_h_
//---------------------------------------------------------------------------------
