/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_zapper_h_
#define _control_zapper_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_zapper[];
extern const int control_zapper_size;
//---------------------------------------------------------------------------------
#endif //_control_zapper_h_
//---------------------------------------------------------------------------------
