/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _control_wiimote_h_
#define _control_wiimote_h_
//---------------------------------------------------------------------------------
extern const unsigned char control_wiimote[];
extern const int control_wiimote_size;
//---------------------------------------------------------------------------------
#endif //_control_wiimote_h_
//---------------------------------------------------------------------------------
