/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _date_highlight_h_
#define _date_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char date_highlight[];
extern const int date_highlight_size;
//---------------------------------------------------------------------------------
#endif //_date_highlight_h_
//---------------------------------------------------------------------------------
