/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _delete_button_h_
#define _delete_button_h_
//---------------------------------------------------------------------------------
extern const unsigned char delete_button[];
extern const int delete_button_size;
//---------------------------------------------------------------------------------
#endif //_delete_button_h_
//---------------------------------------------------------------------------------
