/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _download_frame_h_
#define _download_frame_h_
//---------------------------------------------------------------------------------
extern const unsigned char download_frame[];
extern const int download_frame_size;
//---------------------------------------------------------------------------------
#endif //_download_frame_h_
//---------------------------------------------------------------------------------
