/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _down_highlight_h_
#define _down_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char down_highlight[];
extern const int down_highlight_size;
//---------------------------------------------------------------------------------
#endif //_down_highlight_h_
//---------------------------------------------------------------------------------
