/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_ratings_h_
#define _help_ratings_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_ratings[];
extern const int help_ratings_size;
//---------------------------------------------------------------------------------
#endif //_help_ratings_h_
//---------------------------------------------------------------------------------
