/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_settings_6_h_
#define _help_settings_6_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_settings_6[];
extern const int help_settings_6_size;
//---------------------------------------------------------------------------------
#endif //_help_settings_6_h_
//---------------------------------------------------------------------------------
