/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_highlight_h_
#define _help_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_highlight[];
extern const int help_highlight_size;
//---------------------------------------------------------------------------------
#endif //_help_highlight_h_
//---------------------------------------------------------------------------------
