/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_about_h_
#define _help_about_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_about[];
extern const int help_about_size;
//---------------------------------------------------------------------------------
#endif //_help_about_h_
//---------------------------------------------------------------------------------
