/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _help_download_update_2_h_
#define _help_download_update_2_h_
//---------------------------------------------------------------------------------
extern const unsigned char help_download_update_2[];
extern const int help_download_update_2_size;
//---------------------------------------------------------------------------------
#endif //_help_download_update_2_h_
//---------------------------------------------------------------------------------
