/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _menu_reboot_highlight_h_
#define _menu_reboot_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char menu_reboot_highlight[];
extern const int menu_reboot_highlight_size;
//---------------------------------------------------------------------------------
#endif //_menu_reboot_highlight_h_
//---------------------------------------------------------------------------------
