/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _menu_reboot_h_
#define _menu_reboot_h_
//---------------------------------------------------------------------------------
extern const unsigned char menu_reboot[];
extern const int menu_reboot_size;
//---------------------------------------------------------------------------------
#endif //_menu_reboot_h_
//---------------------------------------------------------------------------------
