/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _menu_settings_h_
#define _menu_settings_h_
//---------------------------------------------------------------------------------
extern const unsigned char menu_settings[];
extern const int menu_settings_size;
//---------------------------------------------------------------------------------
#endif //_menu_settings_h_
//---------------------------------------------------------------------------------
