/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _sd_card_highlight_h_
#define _sd_card_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char sd_card_highlight[];
extern const int sd_card_highlight_size;
//---------------------------------------------------------------------------------
#endif //_sd_card_highlight_h_
//---------------------------------------------------------------------------------
