/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _sort_arrow_up_h_
#define _sort_arrow_up_h_
//---------------------------------------------------------------------------------
extern const unsigned char sort_arrow_up[];
extern const int sort_arrow_up_size;
//---------------------------------------------------------------------------------
#endif //_sort_arrow_up_h_
//---------------------------------------------------------------------------------
