/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _star_highlight_h_
#define _star_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char star_highlight[];
extern const int star_highlight_size;
//---------------------------------------------------------------------------------
#endif //_star_highlight_h_
//---------------------------------------------------------------------------------
