/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tool_tip_queue_h_
#define _tool_tip_queue_h_
//---------------------------------------------------------------------------------
extern const unsigned char tool_tip_queue[];
extern const int tool_tip_queue_size;
//---------------------------------------------------------------------------------
#endif //_tool_tip_queue_h_
//---------------------------------------------------------------------------------
