/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tool_tip_sort_name_h_
#define _tool_tip_sort_name_h_
//---------------------------------------------------------------------------------
extern const unsigned char tool_tip_sort_name[];
extern const int tool_tip_sort_name_size;
//---------------------------------------------------------------------------------
#endif //_tool_tip_sort_name_h_
//---------------------------------------------------------------------------------
