/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _update_highlight_h_
#define _update_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char update_highlight[];
extern const int update_highlight_size;
//---------------------------------------------------------------------------------
#endif //_update_highlight_h_
//---------------------------------------------------------------------------------
