/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _updated_close_highlight_h_
#define _updated_close_highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char updated_close_highlight[];
extern const int updated_close_highlight_size;
//---------------------------------------------------------------------------------
#endif //_updated_close_highlight_h_
//---------------------------------------------------------------------------------
