/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _GRRLIB_font1_h_
#define _GRRLIB_font1_h_
//---------------------------------------------------------------------------------
extern const unsigned char GRRLIB_font1[];
extern const int GRRLIB_font1_size;
//---------------------------------------------------------------------------------
#endif //_GRRLIB_font1_h_
//---------------------------------------------------------------------------------
